Fix missing FL include
This fixes the following error which seems to be due to newer FL
versions:

```
  src/UI/MasterUI.cxx:2381:3: error: 'fl_open_display' was not declared in this scope
```

This also fixes 2 deprecation warnings since FLTK 1.4.4.